steps:
  - name: "gcr.io/cloud-builders/curl:latest"
    id: "fetch-firebase-binary"
    args:
      - "--silent"
      - "--location"
      - "--output"
      - "/workspace/firebase"
      - "https://firebase.tools/bin/linux/latest"
  - name: "gcr.io/cloud-builders/curl:latest"
    id: "fetch-hugo-binary"
    args:
      - "--silent"
      - "--location"
      - "--output"
      - "/workspace/hugo.tar.gz"
      - "https://github.com/gohugoio/hugo/releases/download/v${_HUGO_VERSION}/hugo_extended_${_HUGO_VERSION}_Linux-64bit.tar.gz"
    waitFor: ["fetch-firebase-binary"]
  - name: "golang:1"
    id: "extract-and-deploy"
    env:
    - "PROJECT_ID=${PROJECT_ID}"
    - "BUILD_ID=${BUILD_ID}"
    - "SHORT_SHA=${SHORT_SHA}"
    - "_CHANNEL_ID=${_CHANNEL_ID}"
    - "_EXPIRE_TIME=${_EXPIRE_TIME}"
    script: |
      #!/usr/bin/env bash

      # Prepare Firebase CLI
      mkdir -p /tmp
      mv firebase /tmp
      chmod 755 /tmp/firebase
      echo "Firebase CLI version: $(/tmp/firebase --version | awk '{print $NF}')"

      # Extract Hugo
      mv hugo.tar.gz /tmp
      tar -C /tmp -xzf /tmp/hugo.tar.gz

      # Clean up the public directory
      cd /workspace/public/
      files=$(ls)
      if [[ ! -z "$files" ]]; then
        rm -r *
      fi

      # Build with Hugo
      cd /workspace/hugo
      if [[ "$_CHANNEL_ID" == "production" ]]; then
        export HUGO_ENV="production"
        /tmp/hugo --cleanDestinationDir --gc --minify --environment production

        # Clean up theme-ananke sample
        rm /workspace/public/images/gohugo-default-sample-hero-image.jpg

        cd /workspace/
        /tmp/firebase --project ${PROJECT_ID} --non-interactive deploy --only hosting -m "Build ${BUILD_ID}"
      else
        /tmp/firebase --project ${PROJECT_ID} --non-interactive hosting:channel:delete ${SHORT_SHA} --force
        /tmp/firebase --project ${PROJECT_ID} --non-interactive hosting:channel:create ${SHORT_SHA}
        /tmp/hugo --cleanDestinationDir --gc --minify --environment development --buildFuture

        # Clean up theme-ananke sample
        rm /workspace/public/images/gohugo-default-sample-hero-image.jpg

        cd /workspace/
        /tmp/firebase --project ${PROJECT_ID} --non-interactive hosting:channel:deploy ${SHORT_SHA} --expires ${_EXPIRE_TIME}
      fi
    waitFor: ["fetch-hugo-binary"]
substitutions:
  _HUGO_VERSION: 0.139.3
options:
  logging: CLOUD_LOGGING_ONLY
timeout: "300s"
