publishDir = "../public"
baseURL = "https://www.iaeste.or.jp/"
languageCode = "ja"
title = "IAESTE Japan"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
DefaultContentLanguage = "ja"
#SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = false

[menu]
[[menu.main]]
  name = "News"
  pageRef = "news"
  weight = 10
[[menu.main]]
  name = "About IAESTE"
  pageRef = "about"
  weight = 20
[[menu.main]]
  name = "Students"
  pageRef = "students"
  weight = 30
[[menu.main]]
  name = "Companies / Universities"
  pageRef = "employers"
  weight = 40
[[menu.main]]
  name = "Internship"
  pageRef = "internship"
  weight = 50
[[menu.main]]
  name = "Organization"
  pageRef = "org"
  weight = 60
[[menu.main]]
  name = "Contact"
  pageRef = "contact"
  weight = 100

[languages]
  [languages.ja]
    title = "IAESTE Japan"
    weight = 1
    contentDir = "content/ja"
    dateFormat = "2006/01/02"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
tag = "tags"
category = "categories"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "favicon.ico"
  site_logo = "/common/long_iaestejapan.png"
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  recent_posts_number = 3
  mainSections = ["news"]
  custom_css = ["custom.css"]
[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/iaestejp_tokyo"
[[params.ananke_socials]]
  name = "instagram"
  url = "https://www.instagram.com/iaeste_japan/"
[[params.ananke_socials]]
  name = "facebook"
  url = "https://www.facebook.com/iaeste.japan/"
