# This his the main configuration file. There are also environment specific configuration stored in the /config directory.

baseURL                = "https://www.iaeste.or.jp/"
DefaultContentLanguage = "ja"
languageCode           = "ja"
Paginate               = 9
timeZone               = "Asia/Tokyo"
enableRobotsTXT        = false
hasCJKLanguage         = true
publishDir             = "../public"
contentDir             = "content/ja"
title                  = "IAESTE Japan"
theme                  = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[services]
  [services.googleAnalytics]
    ID = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
tag = "tags"
category = "categories"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  date_format = "2006年January2日"
  text_color = ""
  author = ""
  favicon = "favicon.ico"
  site_logo = "/common/long_iaestejapan.png"
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  recent_posts_number = 3
  mainSections = ["news"]
  custom_css = ["custom.css"]
[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/iaestejp_tokyo"
[[params.ananke_socials]]
  name = "instagram"
  url = "https://www.instagram.com/iaeste_japan/"
[[params.ananke_socials]]
  name = "facebook"
  url = "https://www.facebook.com/iaeste.japan/"
